version: '3'
services:
  soa-users-app:
    container_name: soa-users-app
    build:
      context: ./soa-users-app/
      dockerfile: Dockerfile
    volumes:
      - ./soa-users-app:/soa-users-app/volume
    env_file:
      - ./soa-users-app/.env.local
    ports:
      - 8000:5000
    depends_on:
      - keycloak
    restart: on-failure

  soa-football-app:
    container_name: soa-football-app
    build:
      context: ./soa-football-app/
      dockerfile: Dockerfile
    volumes:
      - ./soa-football-app:/soa-football-app/volume
    env_file:
      - ./soa-football-app/.env.local
    ports:
      - 8001:5000
    restart: on-failure

  soa-payment-app:
    container_name: soa-payment-app
    build:
      context: ./soa-payment-app/
      dockerfile: Dockerfile
    volumes:
      - ./soa-payment-app:/soa-payment-app/volume
    env_file:
      - ./soa-payment-app/.env.local
    ports:
      - 8002:5000
    depends_on:
      - soa-payment-app-db
    restart: on-failure
    
  soa-betting-app:
    container_name: soa-betting-app
    build:
      context: ./soa-betting-app/
      dockerfile: Dockerfile
    volumes:
      - ./soa-betting-app:/soa-betting-app/volume
    env_file:
      - ./soa-betting-app/.env.local
    ports:
      - 8003:5000
    depends_on:
      - soa-betting-app-db
    restart: on-failure

  soa-betting-app-db:
    image: postgres
    container_name: soa-betting-app-db
    volumes:
      - betting-app-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: betting-app
      POSTGRES_USER: betting-app
      POSTGRES_PASSWORD: betting-app
    ports:
      - 5432:5432

  soa-payment-app-db:
    image: postgres
    container_name: soa-payment-app-db
    volumes:
      - payment-app-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: payment-app
      POSTGRES_USER: payment-app
      POSTGRES_PASSWORD: payment-app
    ports:
      - 5433:5432

  keycloak-db:
    image: postgres
    container_name: keycloak_db
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
    command: start-dev
    
volumes:
  keycloak-data:
  betting-app-data:
  payment-app-data:
