version: '3'
services:
  # soa-users-app:
  #   container_name: soa-users-app
  #   build:
  #     context: ./soa-users-app/
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./soa-users-app:/soa-users-app/volume
  #   env_file:
  #     - ./soa-users-app/.env.local
  #   ports:
  #     - 8005:5000
  #   depends_on:
  #     - keycloak
  #   restart: on-failure

  postgres:
    image: postgres
    container_name: keycloak_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres
    command: start-dev

  # soa-football-query-app-db:
  #   container_name: soa-football-query-app-db
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=soa-football-query-app
  #     - POSTGRES_PASSWORD=soa-football-query-app
  #     - POSTGRES_DB=soa-football-query-app
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
